### ISSUE TITLE
Ember Errors when running locally

### ISSUE THREAD

**Issue by jmdfm** [usecanvas/web-v2#4]
Hey folks, some bugs seem to be in the current master. Not sure if really bugs, or just Ember. 

I'm running everything locally on my own machine and so far so good - however - when I try to create a new canvas there's a bunch of console errors that prevent the canvas from operating. 

The first is an error about injecting an unknown service `flashMessage`:

```
error-handling.js:14 Uncaught Error: Attempting to inject an unknown injection: 'service:flashMessage'
```

I tracked down this file https://github.com/usecanvas/web-v2/blob/master/app/components/routes/canvas-show/component.js#L48 where `flashMessage` is used and every other invocation seems to be `flashMessages`. Changing this to `flashMessages` makes this error go away. 

Now, you get a second console error about:

```
error-handling.js:14 Uncaught Error: Attempting to inject an unknown injection: 'service:router'
```

I tracked this down to the file https://github.com/usecanvas/web-v2/blob/master/app/components/canvas-title-actions/component.js#L6, and commenting this line out makes the app usable.

**Comment by max** [comment]
Can you try this branch? I added an npm shrinkwrap file to pin down some dependencies. https://github.com/usecanvas/web-v2/pull/3/commits/c750635ffe4af6ef6a2da6e9aa977bec4b33d4f9

**Comment by jmdfm** [comment]
@max Does the trick 👌

**Comment by max** [comment]
Cool. I'll have to dig in and see what broke upstream. But will merge this
first.
